### ISSUE TITLE
gmlToJson

### ISSUE THREAD

**Issue by Rajaune** [STEMLab/3DINV#5]
hello ! 

I can not convert my indoorgml file using the gmlToJson.js. It throws an error that I really don't understand: 
Error: Element [{http://www.opengis.net/indoorgml/1.0/core}core:cellSpaceGeometry] could not be unmarshalled as is not known in this context and the property does not allow DOM content.

How can I fix that please ?

**Comment by suheeeee** [comment]
I expect that this error occurred because you ran the code using the 1.0.3 version of the indoor GML file. 
This project suspended a long time ago, so 'gmlToJson ' only supports version 1.0.1 in operation.
If you want to convert an indoor GML file to a json file, check the 'indorgml-to-json-convertor ' part of the STEMLab/indorgml-dev repository. (https://github.com/STEMLab/indoorgml-dev.git). 
And if you want to visualize your indoorGML files, see the latest project, InViewer-Desktop (https://github.com/STEMLab/InViewer-Desktop.git). 
Thank you for your interests in our project.
